In [75]:
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

In [77]:
df = pd.read_csv('soybean.csv')
df

date plant-stand   precip     temp hail         crop-hist  \
0    october      normal  gt-norm     norm  yes       same-lst-yr   
1     august      normal  gt-norm     norm  yes  same-lst-two-yrs   
2       july      normal  gt-norm     norm  yes       same-lst-yr   
3       july      normal  gt-norm     norm  yes       same-lst-yr   
4    october      normal  gt-norm     norm  yes  same-lst-two-yrs   
..       ...         ...      ...      ...  ...               ...   
678    april           ?        ?        ?    ?                 ?   
679    april   lt-normal        ?  lt-norm    ?     diff-lst-year   
680     june   lt-normal        ?  lt-norm    ?     diff-lst-year   
681    april   lt-normal        ?  lt-norm    ?       same-lst-yr   
682     june   lt-normal        ?  lt-norm    ?       same-lst-yr   

    area-damaged    severity   seed-tmt germination  ... sclerotia fruit-pods  \
0      low-areas  pot-severe       none      90-100  ...    absent       norm   
1      scattered      severe  fungicide       80-89  ...    absent       norm   
2      scattered      severe  fungicide       lt-80  ...    absent       norm   
3      scattered      severe       none       80-89  ...    absent       norm   
4      scattered  pot-severe       none       lt-80  ...    absent       norm   
..           ...         ...        ...         ...  ...       ...        ...   
678  upper-areas           ?          ?           ?  ...         ?          ?   
679    scattered           ?          ?           ?  ...         ?        dna   
680    scattered           ?          ?           ?  ...         ?        dna   
681  whole-field           ?          ?           ?  ...         ?        dna   
682  whole-field           ?          ?           ?  ...         ?        dna   

    fruit-spots  seed mold-growth seed-discolor seed-size shriveling   roots  \
0           dna  norm      absent        absent      norm     absent    norm   
1           dna  norm      absent        absent      norm     absent    norm   
2           dna  norm      absent        absent      norm     absent    norm   
3           dna  norm      absent        absent      norm     absent    norm   
4           dna  norm      absent        absent      norm     absent    norm   
..          ...   ...         ...           ...       ...        ...     ...   
678           ?     ?           ?             ?         ?          ?       ?   
679           ?     ?           ?             ?         ?          ?  rotted   
680           ?     ?           ?             ?         ?          ?  rotted   
681           ?     ?           ?             ?         ?          ?  rotted   
682           ?     ?           ?             ?         ?          ?  rotted   

                     class  
0    diaporthe-stem-canker  
1    diaporthe-stem-canker  
2    diaporthe-stem-canker  
3    diaporthe-stem-canker  
4    diaporthe-stem-canker  
..                     ...  
678           2-4-d-injury  
679       herbicide-injury  
680       herbicide-injury  
681       herbicide-injury  
682       herbicide-injury  

[683 rows x 36 columns]

In [79]:
previsores = df.iloc[:,0:-1].values
classe = df.iloc[:,-1].values

In [81]:
# Converte a classe para números
le = LabelEncoder()

classe[:] = le.fit_transform(classe[:])
classe

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 

In [124]:
# Converte os previsores para números
le2 = LabelEncoder()
for i in range(0,35):
    previsores[:,i] = le2.fit_transform(previsores[:,i])

# Convertendo para float32
previsores = previsores.astype('float32')

In [126]:
# Converte a classe numérica para dummy
dummy_class = to_categorical(classe)
dummy_class

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [128]:
# Divisão da base de teste e treino
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, dummy_class, test_size=0.3, random_state=0)
x_teste

array([[4., 2., 1., ..., 2., 1., 2.],
       [2., 1., 3., ..., 0., 0., 3.],
       [5., 1., 0., ..., 0., 0., 3.],
       ...,
       [7., 2., 1., ..., 2., 1., 2.],
       [4., 1., 1., ..., 2., 1., 3.],
       [5., 1., 3., ..., 1., 2., 0.]], dtype=float32)

In [130]:
# Criando a rede neural
modelo = Sequential()

# Camada de entrada oculta com a quantidade de previsores (input_dim)
modelo.add(Dense(units=64, input_dim=35, activation='relu'))
# Segunda camada
modelo.add(Dense(units=32))
# Camada de saída com a quantidade de classificadores
modelo.add(Dense(19, activation='softmax'))

C:\Users\rafae\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [132]:
modelo.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │         2,304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 19)             │           627 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,011 (19.57 KB)

 Trainable params: 5,011 (19.57 KB)

 Non-trainable params: 0 (0.00 B)

In [134]:
# Compilação do modelo e configuração dos híper-parâmetros
modelo.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [136]:
# Treinamento e teste do modelo
modelo.fit(x_treino, y_treino, epochs=1000, validation_data=(x_teste,y_teste))

Epoch 1/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.1684 - loss: 3.2160 - val_accuracy: 0.2585 - val_loss: 2.6709
Epoch 2/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3353 - loss: 2.4032 - val_accuracy: 0.3171 - val_loss: 2.3414
Epoch 3/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4001 - loss: 2.0321 - val_accuracy: 0.3805 - val_loss: 2.1292
Epoch 4/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4715 - loss: 1.8312 - val_accuracy: 0.4439 - val_loss: 1.9637
Epoch 5/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4848 - loss: 1.7372 - val_accuracy: 0.4732 - val_loss: 1.8045
Epoch 6/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5625 - loss: 1.5391 - val_accuracy: 0.5317 - val_loss: 1.6915
Epoch 7/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6139 - loss: 1.4294 - val_accuracy: 0.5561 - val_loss: 1.5274
Epoch 8/1000
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6430 - loss: 1.2909 - val_accuracy: 0

In [138]:
previsoes = modelo.predict(x_teste)
previsoes

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


array([[2.51875432e-09, 2.24236079e-08, 3.00550732e-06, ...,
        7.37293391e-08, 1.94442914e-15, 7.63533990e-07],
       [1.54894982e-21, 3.71824741e-36, 2.88856700e-15, ...,
        1.85112274e-13, 3.98209688e-24, 1.65765685e-16],
       [2.22201077e-11, 1.23284508e-29, 8.18968583e-21, ...,
        4.10633205e-28, 1.40274366e-27, 1.50361731e-14],
       ...,
       [7.01611952e-25, 1.11881974e-07, 0.00000000e+00, ...,
        9.75268396e-37, 9.99999881e-01, 8.55040632e-34],
       [9.47719403e-11, 9.81407098e-08, 8.22578186e-11, ...,
        8.65961057e-13, 5.39312663e-04, 2.09561897e-08],
       [2.61511114e-23, 2.38551419e-30, 7.95325320e-07, ...,
        1.99263436e-12, 3.51209201e-14, 7.10610133e-19]], dtype=float32)

In [142]:
y_teste_matriz = [np.argmax(t) for t in y_teste]
y_previsao_matriz = [np.argmax(t) for t in previsoes]

In [144]:
mc = confusion_matrix(y_teste_matriz, y_previsao_matriz)
mc

array([[ 3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0, 24,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,
         0,  0,  0],
       [ 0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  1,  0,  5,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  1,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  1,  0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  1,  0,  2,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 12,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  3,  6,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0

In [146]:
x_teste

array([[4., 2., 1., ..., 2., 1., 2.],
       [2., 1., 3., ..., 0., 0., 3.],
       [5., 1., 0., ..., 0., 0., 3.],
       ...,
       [7., 2., 1., ..., 2., 1., 2.],
       [4., 1., 1., ..., 2., 1., 3.],
       [5., 1., 3., ..., 1., 2., 0.]], dtype=float32)