In [7]:
import numpy as np

In [19]:
mt = np.array([1,2,3,4,5]) # Matriz unidimensional
mt_float = np.array([1,2,3], dtype=np.float64) # Cria uma array com o tipo float
mt_float
mt_float.astype(np.int32) # Converte para int32

array([1, 2, 3])

In [23]:
mtb = np.array([[3,2,1], [1,2,3]]) # Array bidimensional
mtb

array([[3, 2, 1],
       [1, 2, 3]])

In [41]:
mtz = np.empty([3,2], dtype=int) # Array vazia tipificada
mt0 = np.zeros([3,4]) # Matriz 3x4 de zeros

t = np.ones([2,2]) # Matriz 2x2 de 1s
e = np.eye(5)
e # Matriz quadrada

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
mtr = np.random.random((5)) # Matriz aleatória com 5 valores
i = np.random.randn((3))
al = (10*np.random.random((3,4))) # Matriz 3x4 aleatória
al

array([[7.611672  , 6.33039722, 1.43511184, 7.86313154],
       [3.19288191, 0.60924051, 4.02325025, 8.78884171],
       [6.02295071, 6.07297762, 0.10697042, 3.62808322]])

In [55]:
# Sementes
gnr = np.random.default_rng(1) # Semente 1
ale5 = gnr.random(3)

ale6 = gnr.integers(10, size=(3,4))
ale6

array([[8, 9, 2, 3],
       [8, 4, 2, 8],
       [2, 4, 6, 5]], dtype=int64)

In [67]:
j = np.array([1,1,2,3,4,4])
j = np.unique(j) # Remove repetições
print(j)
al.shape # Mostra o formato da matriz

[1 2 3 4]


(3, 4)

In [69]:
# Funções matemáticas
print(al.min())
print(al.max())
print(al.sum())
# etc...

0.10697042475901752
8.788841713947091
55.68550895017247


In [79]:
# Slicers
print(al[:-1])
print(al[2:4])
print(al[0][1])
print(al[1:])
print(al[:], [0]) # Pega todas as linhas e só a primeira coluna

[[7.611672   6.33039722 1.43511184 7.86313154]
 [3.19288191 0.60924051 4.02325025 8.78884171]]
[[6.02295071 6.07297762 0.10697042 3.62808322]]
6.330397219576559
[[3.19288191 0.60924051 4.02325025 8.78884171]
 [6.02295071 6.07297762 0.10697042 3.62808322]]
[[7.611672   6.33039722 1.43511184 7.86313154]
 [3.19288191 0.60924051 4.02325025 8.78884171]
 [6.02295071 6.07297762 0.10697042 3.62808322]] [0]


In [81]:
m = al + al # Soma duas matrizes
m = al * al # Multiplicação etc...
m

array([[15.223344  , 12.66079444,  2.87022367, 15.72626309],
       [ 6.38576381,  1.21848103,  8.04650049, 17.57768343],
       [12.04590143, 12.14595524,  0.21394085,  7.25616643]])

In [87]:
# transposição, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
print(f)
s = f.T # Transposição linhas para colunas
print("---\n",s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [89]:
# Expressões lógicas
v = np.random.randn(4,4)
print(v)
# Matriz de booleanos
x = (v>0)
# Cria matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x>0,1,-1)
print(z)

[[ 1.49647131 -1.31113322  1.1544087  -0.37313035]
 [-1.57033454  1.15988289 -0.81294476 -0.62076669]
 [-0.62616294  2.67258492  1.28019076  0.20425334]
 [ 0.30193078  1.47271025  0.41941043 -0.67267984]]
[[ 1 -1  1 -1]
 [-1  1 -1 -1]
 [-1  1  1  1]
 [ 1  1  1 -1]]
