In [61]:
# 1- Criar uma função retorna o desenho de uma árvore derivando do tamanho passado. ex:. criarArvore(3)
def tree_builder(size):
    for x in range(size):
        # Espaços
        spaces = '  ' * (size - x - 1)
        # Asteriscos
        asterisks = ' '.join(['*'] * (2 * x + 1))
        print(spaces + asterisks)
    
tree_builder(5)

        *
      * * *
    * * * * *
  * * * * * * *
* * * * * * * * *


In [215]:
# 2-Crie uma função que use recursividade para gerar a sequência de fibonacci.
def fib(n, a=0, b=1, seq=None):
    if n < 1:
        print("Index out of range!")
        return
    if seq is None:
        seq = [a, b] if n > 1 else [a]

    if len(seq) >= n:
        for i in range(2, len(seq)):
            print(f"{seq[i-2]} + {seq[i-1]} = {seq[i]}")
        return seq

    return fib(n, b, a + b, seq + [a + b])

fib(10)

0 + 1 = 1
1 + 1 = 2
1 + 2 = 3
2 + 3 = 5
3 + 5 = 8
5 + 8 = 13
8 + 13 = 21
13 + 21 = 34


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [201]:
# 3-Crie uma função que dado um nome retorna a assinatura da pessoa
def signature(name):
    fullname = name.split(" ")
    try:
        fname = fullname[0]
        mname = fullname[1]
        lname = fullname[-1]
        print(lname.upper() + ", ", fname[0] + ".", mname[0] + ".")
    except IndexError as e:
        print("The name format is wrong, please follow the following pattern: FirstName MiddleName LastName")

signature('Rafael Nascimento Gonçalves')

GONÇALVES,  R. N.


In [239]:
# 4-Crie uma função que retorne a quantidade de dígitos em um número.
def get_length(num):
    num_str = str(num)
    print(len(num_str))
    num = int(num)

get_length("11111")

5


In [247]:
# 5-Crie uma função que receba uma data no formato DD/MM/AAAA e devolva uma string no formato D de mesPorExtenso de AAAA. Opcionalmente, valide a data e retorne NULL caso a data seja inválida.
from datetime import datetime

def format_date(dt):
    months = [
        "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", 
        "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
    ]
    try:
        date = datetime.strptime(dt, "%d/%m/%Y")
        day = date.day
        month = months[date.month -1]
        year = date.year
        return f"{day} de {month} de {year}"
    except ValueError as e:
        return None

print(format_date("19/11/2024"))

19 de Novembro de 2024


In [265]:
# 6-Usando compresão de lista, list comprehension, crie uma função que retorna uma lista com os n primeiros primos solicitados.
def lst_comp(n):
    primes = [num for num in range(2, n+1) if all(num % i != 0 for i in range(2, int(num**0.5) + 1))]
    return primes

print(lst_comp(20))

[2, 3, 5, 7, 11, 13, 17, 19]


In [275]:
# 7-Crie uma função que retorna se duas palavras são anagramas ou não
def is_ang(word1, word2):
    word1 = word1.replace(" ","").lower()
    word2 = word2.replace(" ", "").lower()

    return  "Yes" if sorted(word1) == sorted(word2) else "No"

print(is_ang("night", "thing"))

Yes


In [7]:
'''
[DESAFIO] Criar uma função que faça uma matriz espiral partindo do centro que deriva de acordo com o tamanho de voltas solicitadas.

Foi bem difícil isso aqui 😱, precisei de ajuda aqui, se não, não conseguiria nem entender o problema...
'''
import numpy as np

def generate_spiral(n):
    matrix = np.zeros((n, n), dtype=int)  # Matriz de zeros
    right = (0,1)
    down = (1,0)
    left = (0,-1)
    up = (-1,0)
    directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
    
    x, y = n // 2, n // 2  # Começando pelo centro da matriz com direções de eixo x e y
    num = 1  # Primeiro número pra preencher
    matrix[x, y] = num
    num += 1
    
    steps = 1 # Passos
    dir = 0 # Direção
    
    while num <= n * n:
        for _ in range(2):
            dx, dy = directions[dir]
            for _ in range(steps):
                x, y = x + dx, y + dy
                if 0 <= x < n and 0 <= y < n:
                    matrix[x, y] = num
                    num += 1
            dir = (dir + 1) % 4 # Muda direção
        
        steps += 1
    
    return matrix

print(generate_spiral(10))

[[ 91  92  93  94  95  96  97  98  99 100]
 [ 90  73  74  75  76  77  78  79  80  81]
 [ 89  72  43  44  45  46  47  48  49  50]
 [ 88  71  42  21  22  23  24  25  26  51]
 [ 87  70  41  20   7   8   9  10  27  52]
 [ 86  69  40  19   6   1   2  11  28  53]
 [ 85  68  39  18   5   4   3  12  29  54]
 [ 84  67  38  17  16  15  14  13  30  55]
 [ 83  66  37  36  35  34  33  32  31  56]
 [ 82  65  64  63  62  61  60  59  58  57]]
